ci: add test summary check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,7 +45,7 @@ jobs:
       - name: go vet
         run: just vet
 
-  test:
+  test-matrix:
     name: Test Go ${{ matrix.go-version }}
     runs-on: ubuntu-latest
     strategy:
@@ -68,3 +68,17 @@ jobs:
 
       - name: Test
         run: just test-ci
+
+  test:
+    name: Test
+    runs-on: ubuntu-latest
+    needs:
+      - test-matrix
+    if: ${{ always() }}
+    steps:
+      - name: Check test matrix
+        run: |
+          if [[ "${{ needs.test-matrix.result }}" != "success" ]]; then
+            echo "test matrix failed with result: ${{ needs.test-matrix.result }}"
+            exit 1
+          fi
